// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBMLxxMPYQupcMrLVD0weyb632GXqHsKI',
    appId: '1:608271859649:web:8b46e5eaffb33ab3b23940',
    messagingSenderId: '608271859649',
    projectId: 'android-development-42684',
    authDomain: 'android-development-42684.firebaseapp.com',
    storageBucket: 'android-development-42684.appspot.com',
    measurementId: 'G-KBGTDZ6X06',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxug2cljbI-WhEpFIc5orq_i9w_HOGy8k',
    appId: '1:608271859649:android:66abeb4b682eb2ffb23940',
    messagingSenderId: '608271859649',
    projectId: 'android-development-42684',
    storageBucket: 'android-development-42684.appspot.com',
  );
}
